apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-test
  namespace: np-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi-test
  source:
    repoURL: https://github.com/CharlieBGoodQventus/fastapi-test.git
    path: chart/fastapi-test
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - values-qa.yaml
      parameters:
      - name: "rollout.enabled"
        value: "true"
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
